apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: logstash:YOUR_TAG
          ports:
            - containerPort: 5044
            - containerPort: 50000
            - containerPort: 9600
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/logstash/config/logstash.yml
              subPath: logstash.yml
            - name: pipeline-volume
              mountPath: /usr/share/logstash/pipeline
            - name: data-volume
              mountPath: /var/log/data
          env:
            - name: LS_JAVA_OPTS
              value: "-Xms256m -Xmx256m"
            - name: LOGSTASH_INTERNAL_PASSWORD
              value: ""
          resources:
            limits:
              memory: "512Mi"
              cpu: "0.5"
            requests:
              memory: "256Mi"
              cpu: "0.25"
      volumes:
        - name: config-volume
          hostPath:
            path: /storage01/docker_data/logstash/config/
            type: Directory
        - name: pipeline-volume
          hostPath:
            path: /storage01/docker_data/logstash/pipeline/
            type: Directory
        - name: data-volume
          hostPath:
            path: /storage01/docker_data/logstash/data/
            type: Directory
      restartPolicy: Always
