ARG ELASTIC_VERSION

FROM docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
#RUN apt update && apt install nano -y
# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
