version: '3.7'

services:

  logstash:
    build:
      context: logstash/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - /data/jenkins-agent/workspace/elasticsearch/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - /data/jenkins-agent/workspace/elasticsearch/logstash/config/:/etc/logstash
      - /data/jenkins-agent/workspace/elasticsearch/logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
      - /data/jenkins-agent/workspace/elasticsearch/logstash/data:/var/log/data/:rw
    ports:
      - 5044:5044
      - 50000:50000/tcp
      - 50000:50000/udp
      - 9600:9600
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
    networks:
      - elk
    restart: unless-stopped

