ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}
#RUN logstash-plugin install --no-verify logstash-input-syslog
#RUN apt update && apt install nano -y
# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
